# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - name: search-service
    url: http://search_service:8080  # URL interna del microservicio de productos
    routes:
      - name: search-by-id
        paths:
          - /product/id
        methods:
          - GET
        strip_path: false
upstreams:
  - name: localhost
    targets:
      - target: search_service:8080
        weight: 100
